import type { Finding, Severity } from "./types.js";
import { scoreFindings, type Scorecard } from "./scorecard.js";

const GRADE_COLORS: Record<string, string> = {
  "A+": "#10b981",
  A: "#22c55e",
  B: "#84cc16",
  C: "#eab308",
  D: "#f97316",
  F: "#ef4444",
};

const SEVERITY_COLORS: Record<Severity, string> = {
  CRITICAL: "#dc2626",
  HIGH: "#ea580c",
  MEDIUM: "#ca8a04",
  LOW: "#0ea5e9",
};

export function renderHtmlReport(
  scanId: string,
  findings: Finding[],
  projectName: string | null = null
): string {
  const card = scoreFindings(findings);
  const grouped: Record<Severity, Finding[]> = {
    CRITICAL: [],
    HIGH: [],
    MEDIUM: [],
    LOW: [],
  };
  for (const f of findings) grouped[f.severity].push(f);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>claude-guard report${projectName ? ` — ${escapeHtml(projectName)}` : ""}</title>
<style>
  :root {
    --bg: #0b1020;
    --panel: #121832;
    --text: #e6ecff;
    --muted: #99a2c9;
    --accent: #7c3aed;
    --border: #1f2a52;
    --grade: ${GRADE_COLORS[card.grade] ?? "#6b7280"};
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--bg); color: var(--text); font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; line-height: 1.55; }
  .wrap { max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem 4rem; }
  header { display: flex; align-items: center; gap: 1.5rem; flex-wrap: wrap; margin-bottom: 2rem; }
  .brand { font-weight: 700; letter-spacing: -0.02em; font-size: 1.25rem; }
  .brand span { color: var(--muted); font-weight: 500; margin-left: .5rem; }
  .grade { display: inline-flex; align-items: center; justify-content: center; width: 5rem; height: 5rem; border-radius: 999px; background: var(--grade); color: #0b1020; font-weight: 800; font-size: 1.75rem; box-shadow: 0 6px 24px color-mix(in srgb, var(--grade) 40%, transparent); }
  .headline { font-size: 1rem; color: var(--muted); }
  .headline strong { color: var(--text); }
  .card { background: var(--panel); border: 1px solid var(--border); border-radius: 16px; padding: 1.25rem 1.5rem; }
  .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: .75rem; margin-bottom: 2rem; }
  .stat { text-align: center; padding: 1rem .5rem; background: var(--panel); border: 1px solid var(--border); border-radius: 12px; }
  .stat .n { font-size: 1.5rem; font-weight: 700; }
  .stat .l { font-size: .75rem; color: var(--muted); letter-spacing: .08em; text-transform: uppercase; }
  .section { margin-bottom: 1.5rem; }
  .section h2 { margin: 0 0 .75rem; font-size: 1rem; letter-spacing: .08em; text-transform: uppercase; color: var(--muted); }
  details.finding { border: 1px solid var(--border); border-radius: 12px; padding: .75rem 1rem; margin-bottom: .5rem; background: var(--panel); }
  details.finding summary { cursor: pointer; list-style: none; display: flex; gap: .75rem; align-items: baseline; }
  details.finding summary::-webkit-details-marker { display: none; }
  .chip { display: inline-flex; align-items: center; padding: .15rem .55rem; border-radius: 999px; font-size: .7rem; font-weight: 700; letter-spacing: .05em; }
  .rule-id { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; color: var(--muted); font-size: .85rem; }
  .title { flex: 1; }
  .loc { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; color: var(--muted); font-size: .8rem; }
  .ev { margin-top: .75rem; padding: .75rem; background: #0a0f25; border-radius: 8px; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .8rem; overflow-x: auto; }
  .hint { margin-top: .5rem; color: var(--muted); white-space: pre-wrap; font-size: .9rem; }
  footer { margin-top: 2rem; color: var(--muted); font-size: .8rem; text-align: center; }
</style>
</head>
<body>
<div class="wrap">
  <header>
    <div class="grade">${escapeHtml(card.grade)}</div>
    <div>
      <div class="brand">claude-guard<span>scan ${escapeHtml(scanId.slice(0, 8))}</span></div>
      <div class="headline">Score <strong>${card.score}/100</strong> · ${escapeHtml(card.headline)}</div>
    </div>
  </header>

  <div class="stats">
    ${(["CRITICAL", "HIGH", "MEDIUM", "LOW"] as Severity[])
      .map((s) => `
    <div class="stat">
      <div class="n" style="color:${SEVERITY_COLORS[s]}">${card.finding_counts[s]}</div>
      <div class="l">${s}</div>
    </div>`).join("")}
  </div>

  ${(["CRITICAL", "HIGH", "MEDIUM", "LOW"] as Severity[])
    .filter((s) => grouped[s].length > 0)
    .map((s) => renderSection(s, grouped[s]))
    .join("\n")}

  <footer>
    Generated by claude-guard. Open <code>.claude-guard/findings.md</code> to toggle items for <code>apply_fixes</code>.
  </footer>
</div>
</body>
</html>
`;
}

function renderSection(sev: Severity, findings: Finding[]): string {
  return `<div class="section">
  <h2>${sev} (${findings.length})</h2>
  ${findings.map((f) => renderFinding(sev, f)).join("")}
</div>`;
}

function renderFinding(sev: Severity, f: Finding): string {
  return `<details class="finding">
    <summary>
      <span class="chip" style="background:${SEVERITY_COLORS[sev]};color:#fff">${sev}</span>
      <span class="rule-id">${escapeHtml(f.rule_id)}</span>
      <span class="title">${escapeHtml(f.message)}</span>
      <span class="loc">${escapeHtml(f.file)}:${f.range.startLine}</span>
    </summary>
    <div class="ev">${escapeHtml(f.evidence)}</div>
    ${f.fix_hint ? `<div class="hint">${escapeHtml(f.fix_hint.trim())}</div>` : ""}
  </details>`;
}

function escapeHtml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

export function renderHtmlReportForCli(card: Scorecard): string {
  void card;
  return "";
}
